using CommandLine;

namespace DbTransfer.Tests;

/// <summary>
/// CLI の各動詞に対応する生成済みコマンド資料が欠けていないことを検証します。
/// </summary>
public sealed class DocumentationTests
{
    /// <summary>
    /// 登録された動詞をリフレクションで列挙し、同名の生成済み Markdown が存在することを確認します。
    /// </summary>
    [Fact]
    public void Every_cli_verb_has_a_generated_command_page()
    {
        var repositoryRoot = FindRepositoryRoot();
        var verbs = typeof(CopyOptions).Assembly.GetTypes()
            .Select(type => type.GetCustomAttributes(typeof(VerbAttribute), false).SingleOrDefault())
            .OfType<VerbAttribute>()
            .Select(attribute => attribute.Name)
            .Order(StringComparer.Ordinal)
            .ToArray();

        Assert.NotEmpty(verbs);

        foreach (var verb in verbs)
        {
            var path = Path.Combine(repositoryRoot, "docs", "commands", $"{verb}.md");
            Assert.True(File.Exists(path), $"Missing generated documentation for '{verb}'.");
            Assert.StartsWith("<!-- Generated by scripts/Generate-CommandDocs.ps1.", File.ReadAllText(path));
        }
    }

    private static string FindRepositoryRoot()
    {
        var directory = new DirectoryInfo(AppContext.BaseDirectory);
        while (directory is not null && !File.Exists(Path.Combine(directory.FullName, "DbTransfer.slnx")))
        {
            directory = directory.Parent;
        }

        return directory?.FullName ?? throw new DirectoryNotFoundException("Could not locate the repository root.");
    }
}
