[CmdletBinding()]
param(
    [string]$Configuration = "Release",
    [string]$OutputDirectory,
    [switch]$NoBuild
)

$ErrorActionPreference = "Stop"
$repoRoot = Split-Path -Parent $PSScriptRoot
$project = Join-Path $repoRoot "src/DbTransfer/DbTransfer.csproj"
if (-not $OutputDirectory) {
    $OutputDirectory = Join-Path $repoRoot "docs/commands"
}

$examples = @{
    copy = @(
        "dbtransfer copy --job jobs/copy-orders.json",
        "dbtransfer copy --job jobs/copy-orders.json --batch-size 2000 --memory-budget-mb 128"
    )
    export = @(
        "dbtransfer export --job jobs/export-orders.json",
        "dbtransfer export --job jobs/export-orders.json | gzip > orders.jsonl.gz"
    )
    import = @(
        "dbtransfer import --job jobs/import-orders.json",
        "gzip -dc orders.jsonl.gz | dbtransfer import --job jobs/import-orders.json"
    )
    exec = @(
        "dbtransfer exec --job jobs/report.json",
        "dbtransfer exec --job jobs/schema-migration.json"
    )
    inspect = @(
        "dbtransfer inspect --job jobs/inspect-orders.json"
    )
    validate = @(
        "dbtransfer validate --job jobs/copy-orders.json"
    )
}

function Invoke-DbTransferHelp {
    param([string[]]$Arguments)

    $dotnetArguments = @("run", "--project", $project, "--configuration", $Configuration, "--no-build")
    $dotnetArguments += "--"
    $dotnetArguments += $Arguments

    $output = & dotnet @dotnetArguments 2>&1 | Out-String
    if ($LASTEXITCODE -notin @(0, 2)) {
        throw "DbTransfer help failed with exit code $LASTEXITCODE.`n$output"
    }

    return (($output.TrimEnd() -split "`r?`n") |
        ForEach-Object { $_ -replace '^DbTransfer .+$', 'DbTransfer <version>' }) -join "`n"
}

if (-not $NoBuild) {
    & dotnet build $project --configuration $Configuration --nologo
    if ($LASTEXITCODE -ne 0) {
        throw "DbTransfer build failed with exit code $LASTEXITCODE."
    }
}

$rootHelp = Invoke-DbTransferHelp -Arguments @("--help")
$commands = foreach ($line in ($rootHelp -split "`n")) {
    if ($line -match '^  (?<name>\S+)\s{2,}(?<description>.+)$' -and $Matches.name -notin @("help", "version")) {
        [pscustomobject]@{ Name = $Matches.name; Description = $Matches.description.Trim() }
    }
}

if (-not $commands) {
    throw "No commands were discovered in the root help output."
}

New-Item -ItemType Directory -Path $OutputDirectory -Force | Out-Null
Get-ChildItem -Path $OutputDirectory -Filter "*.md" -File | Remove-Item
$fence = '```'

foreach ($command in $commands) {
    $help = Invoke-DbTransferHelp -Arguments @($command.Name, "--help")
    $sampleLines = if ($examples.ContainsKey($command.Name)) {
        ($examples[$command.Name] | ForEach-Object { "$fence" + "sh`n$_`n$fence" }) -join "`n`n"
    }
    else {
        "_No usage example has been defined._"
    }

    $content = @"
<!-- Generated by scripts/Generate-CommandDocs.ps1. Do not edit directly. -->

# dbtransfer $($command.Name)

$($command.Description)

> [!NOTE]
> Database connectors are not implemented yet, so these examples document the planned interface.

## Help

$($fence)text
$help
$fence

## Usage examples

$sampleLines
"@
    $path = Join-Path $OutputDirectory "$($command.Name).md"
    [System.IO.File]::WriteAllText($path, $content.TrimEnd() + "`n", [System.Text.UTF8Encoding]::new($false))
}

Write-Host "Generated $($commands.Count) command pages in $OutputDirectory"
